language: node_js

node_js:
  - stable

sudo: false

install:
- npm install

script: true # Skip tests for now, see https://stackoverflow.com/questions/49861126/how-to-configure-travis-ci-to-build-node-js-without-tests

before_deploy:
- npm run build
- cp CNAME .vuepress/dist/CNAME
- cp -ap redirects/. .vuepress/dist
- cp -ap .vuepress/dist/assets/documentation/. .vuepress/dist/documentation
- rm -r .vuepress/dist/assets/documentation

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: .vuepress/dist
  keep-history: true
  name: openEO CI
  email: openeo.ci@uni-muenster.de
  on:
    branch: master