name: Publish openeo.org
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 1" # Weekly run to refresh external resources
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0 # Required for the "last updated" timestamps
      - run: npm install
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
          user_name: 'openEO CI'
          user_email: openeo.ci@uni-muenster.de