name: Publish openeo.org
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 1" # Weekly run to refresh external resources
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--openssl-legacy-provider" # https://github.com/vuejs/vue-cli/issues/6770
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: npm install
      - run: npm run build
      - run: cp CNAME .vuepress/dist/CNAME
      - run: cp -ap redirects/. .vuepress/dist
      - run: cp -ap .vuepress/dist/assets/documentation/. .vuepress/dist/documentation
      - run: rm -r .vuepress/dist/assets/documentation
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vuepress/dist
          user_name: 'openEO CI'
          user_email: openeo.ci@uni-muenster.de